p8150\_hw1\_sc4935
================
Shiwei Chen
2021-09-29

``` r
library(tidyverse)
```

# Problem 1

### Firstly, we create a data frame include 4 different type variables.

``` r
problem1_df = 
  tibble(
    norm_samp = rnorm(10),
    ele_great_0 = norm_samp > 0,
    animal = c("Rhinos", "Kittens", "Raccoons", "Goats", "Skunks", "Hedgehogs", "Otters", "Giraffes", "Seals", "Fox"),
    animal_type = factor(c("herbivore", "carnivores", "omnivorous",  "herbivore", "omnivorous", "omnivorous", "carnivores", "herbivore", "carnivores", "omnivorous"))
    )

problem1_df
```

    ## # A tibble: 10 × 4
    ##    norm_samp ele_great_0 animal    animal_type
    ##        <dbl> <lgl>       <chr>     <fct>      
    ##  1    -1.26  FALSE       Rhinos    herbivore  
    ##  2     1.05  TRUE        Kittens   carnivores 
    ##  3     0.332 TRUE        Raccoons  omnivorous 
    ##  4    -0.559 FALSE       Goats     herbivore  
    ##  5    -0.654 FALSE       Skunks    omnivorous 
    ##  6    -0.303 FALSE       Hedgehogs omnivorous 
    ##  7    -0.545 FALSE       Otters    carnivores 
    ##  8    -1.56  FALSE       Giraffes  herbivore  
    ##  9    -0.842 FALSE       Seals     carnivores 
    ## 10    -1.99  FALSE       Fox       omnivorous

### Secondly, we take the mean of each variable in the dataframe.

``` r
mean(pull(problem1_df, norm_samp))
```

    ## [1] -0.6328136

``` r
mean(pull(problem1_df, ele_great_0))
```

    ## [1] 0.2

``` r
mean(pull(problem1_df, animal))
```

    ## [1] NA

``` r
mean(pull(problem1_df, animal_type))
```

    ## [1] NA

So, the mean of norm\_samp is around -0.43, the mean of ele\_great\_0 is
0.5, but the mean of animal and animal\_type are both NAs.

### Third, we convert variables from one type to another.

``` r
as.numeric(pull(problem1_df, ele_great_0))
as.numeric(pull(problem1_df, animal))
as.numeric(pull(problem1_df, animal_type))
```

We pull the data we required from the data frame, then we use the
as.numeric function to convert variables from one type to another.

In conclusion, since the true or false and the levels of characters can
be easily formatted numbers, the logic variables(ele\_great\_0) are
converted to 0 and 1, and the factor variables(animal\_type) are
converted to 1,2 and 3. But, the strings of the character variables are
not properly formatted numbers, so, when we run the character variables,
it cannot be converted to the numeric class, and only shows NAs.

# Problem 2

## Palmer Penguins Project

``` r
data("penguins", package = "palmerpenguins")
```

### First describe the data in dataset, including the names/values of important variables.

``` r
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts                 |
|:---------------|-----------:|---------------:|:--------|----------:|:----------------------------|
| species        |          0 |           1.00 | FALSE   |         3 | Ade: 152, Gen: 124, Chi: 68 |
| island         |          0 |           1.00 | FALSE   |         3 | Bis: 168, Dre: 124, Tor: 52 |
| sex            |         11 |           0.97 | FALSE   |         2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim\_variable      | n\_missing | complete\_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:--------------------|-----------:|---------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill\_length\_mm    |          2 |           0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill\_depth\_mm     |          2 |           0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper\_length\_mm |          2 |           0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body\_mass\_g       |          2 |           0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year                |          0 |           1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

### Describe the size of data set.

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

So, there are 344 rows and 8 colums within the dataset.

### Calculate the mean flipper length.

``` r
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

So, the mean of flipper length is around 201.

### Scatter Plot

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

![](p8105_hw1_sc4935_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->

``` r
ggsave("penguins_scatter_plot.pdf", height = 6, width = 4)
```
